In [13]:
import pandas as pd

df = pd.read_csv(
    "../data/processed/ai4i_cleaned.csv"
)

print(df.shape)
print(df.columns.tolist())

(10000, 14)
['UDI', 'Product ID', 'Type', 'Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF']

In [14]:
print(df.columns.tolist())

['UDI', 'Product ID', 'Type', 'Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF']

In [15]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [16]:
df = pd.read_csv(
    "../data/processed/ai4i_cleaned.csv"
)

print(df.shape)

df.head()

(10000, 14)

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [17]:
X = df[
    [
        "Air temperature [K]",
        "Process temperature [K]",
        "Rotational speed [rpm]",
        "Torque [Nm]",
        "Tool wear [min]"
    ]
]

y = df["Machine failure"]

print(X.shape)
print(y.shape)

(10000, 5)
(10000,)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(8000, 5)
(2000, 5)

In [19]:
rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf_model.fit(
    X_train,
    y_train
)

RandomForestClassifier(n_estimators=200, random_state=42)

In [20]:
y_pred = rf_model.predict(
    X_test
)

In [21]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy:", accuracy)

print(
    classification_report(
        y_test,
        y_pred
    )
)

Accuracy: 0.9845
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1932
           1       0.86      0.65      0.74        68

    accuracy                           0.98      2000
   macro avg       0.93      0.82      0.87      2000
weighted avg       0.98      0.98      0.98      2000

In [22]:
print(
    confusion_matrix(
        y_test,
        y_pred
    )
)

[[1925    7]
 [  24   44]]

In [23]:
importance = pd.DataFrame(
    {
        "Feature": X.columns,
        "Importance": rf_model.feature_importances_
    }
)

importance.sort_values(
    by="Importance",
    ascending=False
)

                   Feature  Importance
3              Torque [Nm]    0.339121
2   Rotational speed [rpm]    0.208253
4          Tool wear [min]    0.166605
0      Air temperature [K]    0.146980
1  Process temperature [K]    0.139041

In [24]:
import joblib

joblib.dump(
    rf_model,
    "../models/random_forest.pkl"
)

print("Random Forest Saved")

Random Forest Saved

In [25]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy:", accuracy)

Accuracy: 0.9845

In [26]:
print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1932
           1       0.86      0.65      0.74        68

    accuracy                           0.98      2000
   macro avg       0.93      0.82      0.87      2000
weighted avg       0.98      0.98      0.98      2000

In [27]:
print(
    confusion_matrix(
        y_test,
        y_pred
    )
)

[[1925    7]
 [  24   44]]

In [28]:
importance = pd.DataFrame(
    {
        "Feature": X.columns,
        "Importance": rf_model.feature_importances_
    }
)

print(
    importance.sort_values(
        by="Importance",
        ascending=False
    )
)

                   Feature  Importance
3              Torque [Nm]    0.339121
2   Rotational speed [rpm]    0.208253
4          Tool wear [min]    0.166605
0      Air temperature [K]    0.146980
1  Process temperature [K]    0.139041

In [30]:
pip install xgboost

Collecting xgboost
  Using cached xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\komal nikam\code\venv\lib\site-packages (from xgboost) (2.2.6)
Requirement already satisfied: scipy in c:\users\komal nikam\code\venv\lib\site-packages (from xgboost) (1.15.3)
Using cached xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0
Note: you may need to restart the kernel to use updated packages.

In [31]:
from xgboost import XGBClassifier

In [32]:
xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    eval_metric="logloss"
)

In [34]:
X = df[
    [
        "Air temperature [K]",
        "Process temperature [K]",
        "Rotational speed [rpm]",
        "Torque [Nm]",
        "Tool wear [min]"
    ]
].copy()

X.columns = [
    "air_temperature",
    "process_temperature",
    "rotational_speed",
    "torque",
    "tool_wear"
]

y = df["Machine failure"]

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [36]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    eval_metric="logloss"
)

xgb_model.fit(
    X_train,
    y_train
)

print("XGBoost Training Complete")

XGBoost Training Complete

In [37]:
xgb_pred = xgb_model.predict(X_test)

In [38]:
from sklearn.metrics import accuracy_score

print(
    "Accuracy:",
    accuracy_score(y_test, xgb_pred)
)

Accuracy: 0.987

In [39]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        xgb_pred
    )
)

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1932
           1       0.89      0.71      0.79        68

    accuracy                           0.99      2000
   macro avg       0.94      0.85      0.89      2000
weighted avg       0.99      0.99      0.99      2000

In [40]:
from sklearn.metrics import confusion_matrix

print(
    confusion_matrix(
        y_test,
        xgb_pred
    )
)

[[1926    6]
 [  20   48]]

In [41]:
importance = pd.DataFrame(
    {
        "Feature": X.columns,
        "Importance": xgb_model.feature_importances_
    }
)

importance.sort_values(
    by="Importance",
    ascending=False
)

               Feature  Importance
3               torque    0.322130
2     rotational_speed    0.208897
4            tool_wear    0.184858
0      air_temperature    0.165303
1  process_temperature    0.118812

In [42]:
import joblib

joblib.dump(
    xgb_model,
    "../models/xgboost.pkl"
)

print("XGBoost Saved")

XGBoost Saved

In [43]:
from sklearn.ensemble import IsolationForest

In [44]:
X.head()

   air_temperature  process_temperature  rotational_speed  torque  tool_wear
0            298.1                308.6              1551    42.8          0
1            298.2                308.7              1408    46.3          3
2            298.1                308.5              1498    49.4          5
3            298.2                308.6              1433    39.5          7
4            298.2                308.7              1408    40.0          9

In [45]:
iso_model = IsolationForest(
    contamination=0.01,
    random_state=42
)

In [46]:
iso_model.fit(X)

print("Isolation Forest Trained")

Isolation Forest Trained

In [47]:
anomalies = iso_model.predict(X)

print(anomalies[:20])

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

In [48]:
results = pd.DataFrame(
    {
        "actual_failure": y,
        "anomaly_prediction": anomalies
    }
)

results.head()

   actual_failure  anomaly_prediction
0               0                   1
1               0                   1
2               0                   1
3               0                   1
4               0                   1

In [49]:
results["anomaly_prediction"].value_counts()

anomaly_prediction
 1    9900
-1     100
Name: count, dtype: int64

In [50]:
pd.crosstab(
    results["actual_failure"],
    results["anomaly_prediction"]
)

anomaly_prediction  -1     1
actual_failure
0                   73  9588
1                   27   312

In [51]:
import joblib

joblib.dump(
    iso_model,
    "../models/isolation_forest.pkl"
)

print("Isolation Forest Saved")

Isolation Forest Saved

In [52]:
import joblib

best_model = joblib.load(
    "../models/xgboost.pkl"
)

joblib.dump(
    best_model,
    "../models/best_predictive_model.pkl"
)

print("Best Model Saved")

Best Model Saved